import type { Product } from "../lib/product-types";

export type CategoryKey =
  | "sneakers"
  | "caps"
  | "bags"
  | "socks"
  | "t-shirts";

export type ProductArtwork = "shoe" | "shirt" | "cap" | "bag" | "socks";

export type ShopProduct = Product & {
  categoryKey: CategoryKey;
  priceValue: number;
  color: "مشکی" | "سفید" | "آبی" | "خاکی";
  sizes: string[];
  material: "پنبه" | "پلی‌استر" | "چرم" | "کتان ترکیبی سبک";
  inStock: boolean;
  discounted: boolean;
  newestRank: number;
  artwork: ProductArtwork;
};

export const quickCategories: Array<{
  key: "all" | CategoryKey;
  english: string;
  persian: string;
}> = [
  { key: "all", english: "All", persian: "همه" },
  { key: "sneakers", english: "Sneakers", persian: "کتونی" },
  { key: "caps", english: "Caps", persian: "کلاه" },
  { key: "bags", english: "Bags", persian: "کیف" },
  { key: "socks", english: "Socks", persian: "جوراب" },
  { key: "t-shirts", english: "T-Shirts", persian: "تیشرت" },
];

export const shopProducts: ShopProduct[] = [
  {
    id: "daily-sneaker",
    badge: "جدید",
    category: "کتونی",
    categoryKey: "sneakers",
    name: "کتونی شهری مینیمال",
    english: "DAILY SNEAKER",
    price: "۳٬۸۹۰٬۰۰۰ تومان",
    priceValue: 3_890_000,
    color: "سفید",
    sizes: ["M", "L", "XL"],
    material: "چرم",
    inStock: true,
    discounted: false,
    newestRank: 12,
    artwork: "shoe",
    image: "/assets/product-shoe.png",
  },
  {
    id: "essential-tshirt",
    badge: "پرفروش",
    category: "تیشرت",
    categoryKey: "t-shirts",
    name: "تیشرت پنبه‌ای اسنشیال",
    english: "ESSENTIAL T-SHIRT",
    price: "۱٬۴۹۰٬۰۰۰ تومان",
    priceValue: 1_490_000,
    color: "مشکی",
    sizes: ["S", "M", "L", "XL"],
    material: "پنبه",
    inStock: true,
    discounted: true,
    newestRank: 11,
    artwork: "shirt",
    image: "/assets/product-shirt.png",
  },
  {
    id: "sky-blue-cap",
    badge: "جدید",
    category: "کلاه",
    categoryKey: "caps",
    name: "کلاه آبی آسمانی",
    english: "SKY BLUE DAILY CAP",
    price: "۱٬۲۹۰٬۰۰۰ تومان",
    priceValue: 1_290_000,
    color: "آبی",
    colors: ["آبی آسمانی", "مشکی", "خاکی", "خاکستری روشن"],
    sizes: ["Free Size", "Adjustable"],
    material: "کتان ترکیبی سبک",
    inStock: true,
    discounted: false,
    newestRank: 10,
    artwork: "cap",
    image: "/assets/product-cap.png",
  },
  {
    id: "crossbody-bag",
    badge: "جدید",
    category: "کیف",
    categoryKey: "bags",
    name: "کیف دوشی روزمره",
    english: "CROSSBODY BAG",
    price: "۲٬۶۹۰٬۰۰۰ تومان",
    priceValue: 2_690_000,
    color: "خاکی",
    sizes: ["M"],
    material: "چرم",
    inStock: true,
    discounted: false,
    newestRank: 9,
    artwork: "bag",
    image: "/assets/product-bag.png",
  },
  {
    id: "classic-white",
    badge: "",
    category: "کتونی",
    categoryKey: "sneakers",
    name: "کتونی سفید کلاسیک",
    english: "CLASSIC WHITE",
    price: "۴٬۲۹۰٬۰۰۰ تومان",
    priceValue: 4_290_000,
    color: "سفید",
    sizes: ["M", "L"],
    material: "چرم",
    inStock: true,
    discounted: false,
    newestRank: 8,
    artwork: "shoe",
    image: "/assets/product-shoe.png",
  },
  {
    id: "relaxed-black",
    badge: "",
    category: "تیشرت",
    categoryKey: "t-shirts",
    name: "تیشرت مشکی آزاد",
    english: "RELAXED BLACK",
    price: "۱٬۶۹۰٬۰۰۰ تومان",
    priceValue: 1_690_000,
    color: "مشکی",
    sizes: ["S", "M", "L", "XL"],
    material: "پنبه",
    inStock: true,
    discounted: false,
    newestRank: 7,
    artwork: "shirt",
    image: "/assets/product-shirt.png",
  },
  {
    id: "sand-cap",
    badge: "",
    category: "کلاه",
    categoryKey: "caps",
    name: "کلاه خاکی مینیمال",
    english: "SAND CAP",
    price: "۹۴۰٬۰۰۰ تومان",
    priceValue: 940_000,
    color: "خاکی",
    sizes: ["M", "L"],
    material: "پلی‌استر",
    inStock: true,
    discounted: false,
    newestRank: 6,
    artwork: "cap",
    image: "/assets/product-cap.png",
  },
  {
    id: "city-bag",
    badge: "پرفروش",
    category: "کیف",
    categoryKey: "bags",
    name: "کیف شهری مشکی",
    english: "CITY BAG",
    price: "۲٬۹۹۰٬۰۰۰ تومان",
    priceValue: 2_990_000,
    color: "مشکی",
    sizes: ["M"],
    material: "چرم",
    inStock: true,
    discounted: true,
    newestRank: 5,
    artwork: "bag",
    image: "/assets/product-bag.png",
  },
  {
    id: "daily-socks-3pk",
    badge: "",
    category: "جوراب",
    categoryKey: "socks",
    name: "جوراب سه‌تایی روزمره",
    english: "DAILY SOCKS 3PK",
    price: "۶۹۰٬۰۰۰ تومان",
    priceValue: 690_000,
    color: "سفید",
    sizes: ["M", "L"],
    material: "پنبه",
    inStock: true,
    discounted: false,
    newestRank: 4,
    artwork: "socks",
    image: "/assets/product-shirt.png",
  },
  {
    id: "core-socks-2pk",
    badge: "جدید",
    category: "جوراب",
    categoryKey: "socks",
    name: "جوراب نخی دوتایی",
    english: "CORE SOCKS 2PK",
    price: "۵۹۰٬۰۰۰ تومان",
    priceValue: 590_000,
    color: "مشکی",
    sizes: ["M", "L", "XL"],
    material: "پنبه",
    inStock: true,
    discounted: true,
    newestRank: 3,
    artwork: "socks",
    image: "/assets/product-shirt.png",
  },
  {
    id: "signature-cap",
    badge: "",
    category: "کلاه",
    categoryKey: "caps",
    name: "کلاه امضای Gramiss",
    english: "SIGNATURE CAP",
    price: "۱٬۰۹۰٬۰۰۰ تومان",
    priceValue: 1_090_000,
    color: "مشکی",
    sizes: ["M", "L"],
    material: "پلی‌استر",
    inStock: false,
    discounted: false,
    newestRank: 2,
    artwork: "cap",
    image: "/assets/product-cap.png",
  },
  {
    id: "city-tshirt",
    badge: "محدود",
    category: "تیشرت",
    categoryKey: "t-shirts",
    name: "تیشرت شهری سفید",
    english: "CITY T-SHIRT",
    price: "۱٬۷۹۰٬۰۰۰ تومان",
    priceValue: 1_790_000,
    color: "سفید",
    sizes: ["S", "M", "L"],
    material: "پنبه",
    inStock: true,
    discounted: false,
    newestRank: 1,
    artwork: "shirt",
    image: "/assets/product-shirt.png",
  },
];
